Repository openshift/osd-alert-analysis, pull requests merged in 2022-05, with the labels that each got.

#3 Small README changes to assist with install errors
  README.md
Labels: approved, lgtm

#4 Fixed QFlappingShift date boundary and summing bugs
  questions.py
Labels: tide/merge-method-squash, approved, lgtm

#5 Add "Quick Start" section to README
  README.md
Labels: tide/merge-method-squash, approved, lgtm, ok-to-test
